apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-email-alert
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  groups:
    - name: test-email-alert-group
      rules:
        - alert: TestEmailAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Test email alert"
            description: "This is a test alert from kube-prometheus-stack."